[package]
name = "knowledge"
version = "0.1.0"
authors = ["Matthieu Jacquot <matthieu.jacquot.tech@protonmail.ch>"]
edition = "2018"

[dependencies]
rust-embed="3.0.0"
actix-web = "3"
partial_application = "0.2.1"
webbrowser = "0.5.5"
log = "0.4.11"
yaml-rust = "0.4.4"
dashmap = "3.11.10"

[dev_dependencies]
tempfile = "3"
