[package]
name = "git-know"
version = "0.1.0"
authors = ["Matthieu Jacquot <matthieu.jacquot.tech@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed="3.0.0"
actix-web = "3"
partial_application = "0.2.1"
